dist: focal
# group: dev
language: ruby
virt: lxd

# addons:
#   artifacts:
#     s3_region: "us-west-1" # defaults to "us-east-1"

# php:
# # - 7.2
# # - 7.3
# - 7.4
# #- 7.4.1
# - 7.4.2

install: skip
service: docker

script:
- uname -a
- artifacts -V
# - lsb_release -sc
# - docker run hello-world
# - docker ps
# - docker images
# - ruby -v
